<?php
// Settings specific:
$lll["settings"]="Settings";
$lll["globalsettings"]="Global settings";
$lll["settings_necessaryAuthLevel"]="Necessary authentication level for write permission";
$lll["settings_necessaryAuthLevel_expl"]="Basic level means that the program remembers your password and authenticate you authomatically. With Advanced level, you have to log in first.";
$lll["settings_necessaryAuthLevel_".Loginlib_LowLevel]="Advanced level";
$lll["settings_necessaryAuthLevel_".Loginlib_BasicLevel]="Basic level";
$lll["settings_htmlTitle"]="HTML title";
$lll["settings_htmlTitle_expl"]="The content of the TITLE tag in the HTML header of the forum pages";
$lll["settings_htmlKeywords"]="HTML keywords";
$lll["settings_htmlKeywords_expl"]="The 'keywords' META tag in the HTML header of the forum pages. This is used mainly by the search engines to index the pages.";
$lll["settings_htmlDescription"]="HTML description";
$lll["settings_htmlDescription_expl"]="The 'description' META tag in the HTML header of the forum pages. This is used mainly by the search engines to index the pages.";
$lll["settings_modify_form"]="Personalize portal";
$lll["globalsettings_modify_form"]="Customize global portal settings";
$lll["settings_blockSize"]="Block size";
$lll["settings_blockSize_expl"]="The maximum number of list elements that are displayed on one page. ";
$lll["settings_rangeBlockSize"]="Range block size";
$lll["settings_rangeBlockSize_expl"]="The maximum number of blocks that are displayed in the pager tool itself. ";
$lll["settings_headTemplate"]="Head template";
$lll["settings_headTemplate_expl"]="The text you write here will appear in the header section of the generated html page";
$lll["settings_upperTemplate"]="Top template";
$lll["settings_upperTemplate_expl"]="You can define here an HTML section that will appear above the Zorum page content, or give a php filename which will be executed. This feature can be used to integrate Zorum better in an existing site appearance. ";
$lll["settings_lowerTemplate"]="Bottom template";
$lll["settings_lowerTemplate_expl"]="you can define here an HTML section that will appear below the Zorum page content, or give a php filename which will be executed. This feature can be used to integrate Zorum better in an existing site appearance. ";
$lll["settings_textAreaRows"]="Height of the message text area field";
$lll["settings_textAreaRows_expl"]="You can set the size of the message text input box that suits best to your display and browser window size. ";
$lll["settings_textAreaCols"]="Length of the message text area field";
$lll["settings_textAreaCols_expl"]="You can set the size of the message text input box that suits best to your display and browser window size. ";
$lll["settings_showExplanation"]="Show explanation texts";
$lll["settings_showExplanation_expl"]="What you are currently reading is an explanation text. You can hide them or display as text or as an icon with a short help";
$lll["settings_minPasswordLength"]="Minimum length of the user password";
$lll["settings_showExplanation_".Explanation_text]="text mode";
$lll["settings_showExplanation_".Explanation_qhelp]="quickhelp mode";
$lll["settings_showExplanation_".Explanation_no]="no help";
$lll["settings_language"]="Language";
$lll["settings_language_en"]="English";
$lll["settings_language_hu"]="Hungarian";

// Group specific:
$lll["group"]="group";
$lll["groups"]="Groups";
$lll["group_newitem"]="Add new group";
$lll["group_name"]="Name";
$lll["group_comment"]="Comment";
$lll["group_moderator"]="Moderator";
$lll["group_modify_form"]="Modify group";
$lll["group_create_form"]="Create group";
$lll["group_editGroupTitle"]="Edit group members";

// User specific:
$lll["user"]="Benutzer";
$lll["users"]="Benutzer";
$lll["user_newitem"]="Neuen Benutzer hinzufügen";
$lll["user_name"]="Name";
$lll["user_email"]="Email";
$lll["user_lastClickTime"]="Letzter Klick";
$lll["user_password"]="Passwort";
$lll["user_passwordCopy"]="Passwort wiederholen";
$lll["user_create_form"]="Registrieren";
$lll["user_rememberPassword"]="Erinnerung an Passwort";
$lll["user_notes"]="Anmerkungen";
$lll["user_remind_password_form"]="An Passwort erinnern";
$lll["remind_me_pw"]="Ich habe mein Passwort vergessen, bitte senden Sie mir ein neues per Email!";
$lll["remindmail_subj"]="Erinnerung an das Passwort";
$lll["remindmail_text"]="Ihr Benutzername ist: %s\nIhr neues Passwort ist: %s\n Drücken Sie auf den folgenden Link um Ihr Passwort zu aktivieren, versuchen Sie dann einzuloggen in:\n%s\n\nEs wird empfohlen Ihr Passwort danach zu änden.";
$lll["remindmail_sent"]="Es wurde eine Email mit einem neuen Passwort an Sie gesandt";
$lll["writename_to_remind"]="Tragen Sie bitte Ihren Benutzernamen ein und drücken Sie auf OK, und es wird eine Email mit neuem Passwort an Sie gesandt.";
$lll["remind_remind_password_form"]="Erinnerung an das Passwort";
$lll["remind_username"]="Ihr Benutzername";
$lll["invalid_email"]="Ungültiger Benutzername! Der angegebene Benutzer existiert nicht in diesem System.";
$lll["no_user_name"]="Bitte tragen Sie Ihren Benutzernamen ein!";
$lll["no_mail"]="Der angegebene Nutzer hat keine Email Adresse, somit war eine Zustellung nicht möglich!";
$lll["mistypedPassword"]="Das Passwort wurde falsch eingegeben.";
$lll["passwordTooShort"]="Das Passwort muss mindestens %s Buchstaben haben.";
$lll["userAllreadyExists"]="Der ausgewählte Benutzername existiert bereits. Möchten Sie es nocheinmal mit einem anderen Namen versuchen?";
$lll["cannotAcceptCookie"]="Ihr Browser gestattet nicht die Verwendung von Cookies, demzufolge können Sie nicht im LOW LEVEL einloggen.<P>Möchten Sie deshalb im HIGH LEVEL einloggen?";
$lll["wellcomeNewlyRegistered"]="Neuer Benutzer <b>%s</b> ist erfolgreich registriert.";
$lll["loginAsNewlyRegistered"]="Momentan sind Sie als <b>%s</b> eingeloggt.<BR>Möchten Sie unter Ihrem neu registrierten Namen <b>%s</b> einloggen?";
$lll["permission_denied_mistyped_link"]="ZUGRIFF VERWEIGERT, vielleicht haben Sie den Link falsch angegeben.";
$lll["greeting"]="Willkommen <b>%s</b>!";
$lll["loginInvalid"]="Ihr gewähltes Passwort ist nicht zulässig. Wollen Sie es nocheinmal mit einem anderen versuchen?";
$lll["loginCancelled"]="Login abgebrochen";
$lll["never"]="Nie";
$lll["register"]="Registrieren";
$lll["loginDifferrent"]="Login different";
$lll["login"]="Login";
$lll["logout"]="Logout";
$lll["help"]="Help";
$lll["user_login_form"]="Login";
$lll["user_modify_form"]="Benutzer bearbeiten";
$lll["goodbye"]="Auf Wiedersehen <b>%s</b>!";
$lll["return_to_forum"]="Drücken Sie hier um zur Applikation zurückzukehren!";
$lll["changePassword"]="Passwort ändern";
$lll["user_change_password_form"]="Passwort ändern";
$lll["passwordModified"]="Das Passwort wurde erfolgreich geändert.";
$lll["timeoutExpired"]="Timeout expired. Please, log in!";//TODO

// Installation:
$lll["mysql_found"]="MySQL wurde gefunden.";
$lll["need_pw"]="MySQL benötigt ein Passwort für den Nutzer  %s.";
$lll["incorr_pw"]="MySQL Passwort für den Nutzer %s ist falsch.";
$lll["mysql_not_found"]="MySQL nicht gefunden! Bitte ändern Sie unten die Parameter so, wie es Ihrer MySQL Konfiguration entspricht!";
$lll["db_installed"]="%s database wurde installiert: %s.";

$lll["cantcreatedb"]="Unmöglich auf eine Database zuzugreifen oder sie zu erstellen. Benutzer %s ist es nicht gestattet eine Database zu erstellen, oder es ist ihm nicht möglich auf eine zuzugreifen. Ändern Sie den Benutzernamen und ändern Sie seine Authorisierung!";
$lll["cantconnectdb"]="Verbindung konnte nicht mit Database hergestellt werden. Vielleicht sind Sie dazu nicht berechtigt oder die Database ist nicht existent. Das Programm versucht, jetzt eine neue zu erstellen.";
$lll["inst_create_table_err"]="Fehler bei dem Versuch, neue Tabellen zu erzeugen, haben Sie %s vielleicht schon installiert?";
$lll["db_created"]="%s Database %s wurde erstellt.";
$lll["tables_installed"]="%s database Tabellen wurden installiert.";
$lll["fill_table_err"]="Fehler beim Versuch, Tabellen zu füllen.";
$lll["tables_filled"]="Die %s Datenbanktabellen sind mit Initialisierungsdaten gefüllt worden.";
$lll["congrat"]="Glückwunsch! Sie haben %s installiert!";
$lll["inst_click"]="Hier klicken für Zugang zu %s.";
$lll["createTableFailed"]="Fehler beim Versuch, Tabellen zu erstellen";
$lll["install"]="Installieren";
$lll["clickToInstall"]="Klicken Sie auf 'Installieren' %s zu Installieren!";
$lll["php4ok"]="PHP 4 gefunden.";
$lll["php4nok"]="PHP 4 nicht gefunden. Zorum benötigt PHP 4. Bitte downloaden Sie diese Datei bei www.php.net oder von zend.com, anschliessend versuchen Sie diesen Vorgang nocheinmal!";
$lll["admin_ok"]="Administrator Benutzer wurde erstellt, Benutzername: admin, Passwort: admin.";
$lll["create_file_ok"]="Config file wurde erstellt.";
$lll["create_file_nok"]="Config file muss manuell erstellt werden.";
$lll["inst_params"]="MySQL Datenbank wird mit den folgenden Parametern erstellt:";
$lll["edit_params"]="Parameter ändern";
$lll["dbHostName"]="Hostname";
$lll["mysqluser"]="Mysql Benutzer Name";
$lll["dbDbName"]="Datenbank name";
$lll["dbSocket"]="Socket";
$lll["formtitle"]="MySQL Einstellungen";
$lll["password"]="Passwort";
$lll["dbPort"]="Port";
$lll["dbName"]="Datenbank name";
$lll["dbSocket"]="Socket";
$lll["hostName"]="Hostname";
$lll["cookieok"]="Cookies sind zugelassen.";
$lll["cookienok"]="Cookies zulassen und neustarten!";
$lll["conf_file_write_err"]="Nicht möglich die Config Datei zu öffnen für Eintrag ";
$lll["compare_conf"]="Erstellen Sie eine Datei mit einem Text Editor Ihrer Wahl im Verzeichniss von Zorum source, benennen Sie diese in 'config.php'. Nun fügen Sie den folgenden source code ein! Stellen Sie bitte sicher, dass Sie keine neue Zeile nach der letzten anfügen!!!";
$lll["afterwrconf"]="<u>Nach</u> erstellen der Config-Datei klicken Sie den unteren Link an!";
$lll["move_inst_file"]="Bitte entfernen Sie die install.php Datei aus diesem Verzeichnis!";
$lll["inst_ch_pw"]="Administrator Einstellungen - Benutzername: admin, Passwort: admin. Nicht vergessen das Passwort zu ändern!";





// end installation

// System initialization:
$lll["not_found_in_db"]="Not found in the DB.";
$lll["deep_struct"]="Tree structure error, too deep or incorrect.";
$lll["no_father"]="Tree structure error, father not exists.";
// end system initialization:
$lll["not_found_deleted"]="Object not found, may be deleted from the system.";

// Form specific:
$lll["ok"]="Ok";
$lll["cancel"]="Abbrechen";
$lll["back"]="Zurück";
$lll["quickhelp"]="Schnelle Hilfe";
$lll["emptyList"]="(Leere list)";
$lll["nothingSelected"]="(Nichts selektiert)";
$lll["orSelectConcreteTime"]="or select concrete time";
$lll["year"]="Jahr";
$lll["month"]="Monat";
$lll["day"]="Tag";
$lll["month_1"]="January";
$lll["month_2"]="February";
$lll["month_3"]="March";
$lll["month_4"]="April";
$lll["month_5"]="May";
$lll["month_6"]="June";
$lll["month_7"]="July";
$lll["month_8"]="August";
$lll["month_9"]="September";
$lll["month_10"]="October";
$lll["month_11"]="November";
$lll["month_12"]="December";
$lll["youMustSelectOne"]="You must select an item in the list";
$lll["onlyOneCanBeSelected"]="You can't select more than one items for this operation";
$lll["fromListTitle"]="Users outside the group";
$lll["toListTitle"]="Users inside the group";
$lll["addButtonText"]="Add users >>";
$lll["addAllButtonText"]="Add all users >>";
$lll["removeButtonText"]="<< Remove users";
$lll["removeAllButtonText"]="<< Remove all users";
// end form specific:

// Form execution messages
$lll["permission_denied"]="Zugriff verweigert!";
$lll["operation_cancelled"]="Vorgang abgebrochen";
$lll["created"]="Neue %s erfolgreich erstellt.";
$lll["modified"]="%s erfolgreich verändert.";
$lll["deleted"]="%s erfolgreich gelöscht.";
$lll["multipleDeleted"]="%s items from %s have been successfully deleted.";
$lll["cantDeleteTheRest"]="You don't have permission to delete the rest.";
$lll["beforeDelete"]="Sind Sie sicher dass Sie %s löschen wollen?";
$lll["beforeMultipleDelete"]="%s items will be deleted. Do you really want to continue?";
$lll["yes"]="Ja";
$lll["no"]="Nein";
// end form execution messages

// Validity check:
$lll["mustBeInt"]='The form field "%s" must be a number';
$lll["mustBeFloat"]='The form field "%s" must be a float number';
$lll["mustBeGreaterInt"]='The form field "%s" must be greater than or equal to %s';
$lll["mustBeSmallerInt"]='The form field "%s" must be smaller than or equal to %s';
$lll["mustBeString"]='The form field "%s" must be a string';
$lll["mustBeGreaterString"]='The length of the form field "%s" must be minimum %s';
$lll["mandatoryField"]="'%s' ist ein Pflichtfeld!";
$lll["mustBeSmallerString"]='The length of the form field "%s" must be maximum %s';
$lll["invalidDate"]="The given date was invalid";
// end validity check

// Icon alt texts
$lll["icon_desc"]="absteigend";
$lll["icon_asc"]="aufsteigend";
$lll["icon_details"]="details";
$lll["icon_modify"]="ändern";
$lll["icon_delete"]="löschen";
$lll["detail_info"]="%s Details";
//stylesheet
$lll["stylesheet_newitem"]="New Stylesheet";
$lll["stylesheet_create_form"]="Create New Stylesheet";
$lll["stylesheet_modify_form"]="Modify Stylesheet";
$lll["stylesheet_name"]="Name";
$lll["stylesheet_css"]="Stylesheet";
$lll["stylesheet"]="stylesheet";
// end icon alt texts

// Range Selector:
$lll["prev"]="prev";
$lll["next"]="next";
$lll["first"]="first";
$lll["last"]="last";
// end range selector

// Category specific:
$lll["categories"]="Categories";
$lll["category"]="Category";
$lll["category_newitem"]="Create New Category";
$lll["category_create_form"]=$lll["category_newitem"];
$lll["category_modify_form"]="Modify Category";
$lll["subcats"]="Subcategories";

//Items:
$lll["items"]="Items";
$lll["item"]="item";
$lll["item_newitem"]="Add new item";
$lll["item_active"]="Active";
$lll["item_create_form"]="Create item";
$lll["item_modify_form"]="Modify item";
$lll["item_title"]="Title";
$lll["item_cid"]="Category";
$lll["item_cName"]="Category";
$lll["item_clicked"]="Views";

// Other:
$lll["emptylist"]="Die Liste ist leer";
$lll["flood_err"]="Flooding error. The data already has been sent.<br>\nIt seems that you have clicked the reload/refresh button after sending some data to the system.<br>\n<a href=''>Click here to return to the system!</a>";
$lll["popuphelp_tit"]="Popup Hilfe";
// end other
?>
